const productData = [

    {
        id: '0026',
        name: 'Cycle 1',
        price: 5000,
        category: ['Mountain Bike', 'All Drive', '2 Wheel Drive'],
        disPrice: 4600,
        type: 'MTB',
        description: 'Cycle for mountain ride and city ride',
        brand: 'Geekey',
        color: ['blue', 'black', 'red'],
        tag: ['sport', 'speed', 'all terrain'],
        overview: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        mainImg: 'https://ibb.co/yVMby5k',
        subImg: [
            'https://i.ibb.co/g6XBTwW/Web-1920-1-2x.png',
            'https://i.ibb.co/g6XBTwW/Web-1920-1-2x.png',
            'https://i.ibb.co/g6XBTwW/Web-1920-1-2x.png',
            'https://i.ibb.co/g6XBTwW/Web-1920-1-2x.png'
        ],
        frames: 'Steel Frame',
        wheels: 'Alloys',
        weight: "10Kg",
        height: "50Cm",
        dimensions: "10cm 23cm 13cm",
        materials: "60% Steel, 40% Aluminum",
        driveTrain: 'Rock and Hill',
        component: 'Gear Switch',
        accessories: 'Pump and Helmet',
        packingAssembly: 'Packing and Shipping',
        topSpeed: '80kmph',
        topRange: '12 Km',
        rating: 5,
        favroite: true,
        isAvail: true,
        isStock: true,
        isSoldout: true,
        isOffers: true,
        new: true,
        discount: true,
        affiliateLink: '/good'
    },
    {
        id: '0027',
        name: 'Cycle 2',
        price: 8000,
        category: ['Mountain Bike', 'All Drive', '2 Wheel Drive'],
        disPrice: 4600,
        type: 'MTB',
        description: 'Cycle for mountain ride and city ride',
        brand: 'Geekey',
        color: ['blue', 'black', 'red'],
        tag: ['sport', 'speed', 'all terrain'],
        overview: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        mainImg: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8',
        subImg: [
            'https://images.unsplash.com/photo-1665925246453-e7aeb96b3744?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8',
            'https://images.unsplash.com/photo-1664574654578-d5a6a4f447bb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8',
            'https://images.unsplash.com/photo-1665779829294-f2297a628d8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8',
            'https://images.unsplash.com/photo-1665686310934-8fab52b3821b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8'
        ],
        frames: 'Steel Frame',
        wheels: 'Alloys',
        weight: "10Kg",
        height: "50Cm",
        dimensions: "10cm 23cm 13cm",
        materials: "60% Steel, 40% Aluminum",
        driveTrain: 'Rock and Hill',
        component: 'Gear Switch',
        accessories: 'Pump and Helmet',
        packingAssembly: 'Packing and Shipping',
        topSpeed: '80kmph',
        topRange: '12 Km',
        rating: 5,
        favroite: true,
        isAvail: true,
        isStock: true,
        isSoldout: true,
        isOffers: true,
        new: true,
        discount: true,
        affiliateLink: '/good'
    },


]


export { productData }